name: 'telegraph'
description: 'Telegraph Dart Library For interact with api telegraph.'
version: '0.0.4'
repository: 'https://github.com/azkadev/telegraph.git'
homepage: 'https://youtube.com/@azkadev'
issue_tracker: 'https://github.com/azkadev/telegraph.git'
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  general_lib: '^0.0.50'
  http: '^1.2.2'
  http_parser: '^4.0.2'
  markdown: '^7.2.2'
  mime: '^2.0.0'
  path: '^1.9.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
documentation: 'https://youtube.com/@azkadev'
