name: telegraph
description: A Library Telegraph.
version: 0.0.0
repository: https://github.com/azkadev/telegraph.git

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  general_lib: ^0.0.1
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
